/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    extend: {
      colors: {
        primary: '#0058bc',
        'on-primary': '#ffffff',
        'primary-container': '#0070eb',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        secondary: '#405e96',
        'on-secondary': '#ffffff',
        'secondary-container': '#a1befd',
        'on-secondary-container': '#2d4c83',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#26467d',
        tertiary: '#9e3d00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c64f00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb595',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7c2e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf9fe',
        'on-background': '#1a1b1f',
        surface: '#faf9fe',
        'on-surface': '#1a1b1f',
        'surface-variant': '#e3e2e7',
        'on-surface-variant': '#414755',
        'surface-dim': '#dad9df',
        'surface-bright': '#faf9fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'surface-tint': '#005bc1',
        outline: '#717786',
        'outline-variant': '#c1c6d7',
        'inverse-surface': '#2f3034',
        'inverse-on-surface': '#f1f0f5',
        'inverse-primary': '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
}